### ISSUE TITLE
Requirements to run code

### ISSUE THREAD

**Issue by beangoben** [edg2103/odormatic#1]
Hi trying to replicates results from your paper, thanks for making your code available!
What is the required version of software to run your code? (Python, sklearn, gensim, etc.)
Could you provide a conda env to recreate the software stack?

**Comment by beangoben** [comment]
To give an idea, the code does not work with python 2.7, scikit-learn 0.21 (latest) and is missing the wiki-news-300.vec file (easy to find, but would be useful to know you need this file, vs an error).

**Comment by jeriscience** [comment]
Thanks @beangoben the wiki-news-300.vec is way too large to upload here, but we indicated a link. Also the code works with all versions of python 3 >.

Thanks for the interest!
